### ISSUE TITLE
delay getting new values from the input boxes

### ISSUE THREAD

**Issue by antonytrupe** [johnfink8/GravityTurn#2]
Before the guessing functionality, I would change the orbit height from 80 to 100 by deleting the 8 and then typing 10, which made undesired things happen while the value was 0 and 10. One way to solve this is to add a button that "pushes" the new values to the code. I'm sure there are other mechanisms that would also work that I can't think of.

**Comment by antonytrupe** [comment]
cross referencing things
https://github.com/antonytrupe/GravityTurn/issues/1
https://github.com/antonytrupe/GravityTurn/tree/delayed-input

**Comment by johnfink8** [comment]
Latest commit handles input more gracefully, without annoying buttons like some other mods have.
