### ISSUE TITLE
Autostage stages too many

### ISSUE THREAD

**Issue by linuxgurugamer** [johnfink8/GravityTurn#4]
I have a ship which has two boosters and a fairing at the top, looking something like this

cargo/fairing
fairing decoupler
docking port
main stage -> booster decouplers -> boosters

the problem is that when the boosters decouple, it also triggers the fairing, and the cargo then burns up because it is too low in the atmosphere.

Maybe only autostage one at a time,possible doing the next if no thrust is detected after the first stage

Note that if I put a decoupler between the fairing and the main stage, it doesn't seem to autostage that one

**Comment by johnfink8** [comment]
Should be resolved with dda19f1ef90230afba948b7749c628d074b02f19

Stage settings window will now allow you to set the dynamic pressure where the fairings will pop.
