### ISSUE TITLE
Enhancement request: Dismiss button in window

### ISSUE THREAD

**Issue by linuxgurugamer** [johnfink8/GravityTurn#5]
My toolbar is rather full, so it would be nice if there was a button on the dialog to dismiss it

**Comment by johnfink8** [comment]
As an autopilot, this seems like the kind of feature that could be misused.  Let me think about this one for a while.

**Comment by linuxgurugamer** [comment]
My suggestion would be a button to just dismiss the window, as if you clicked the toolbar button.  No functionality other than that

**Comment by johnfink8** [comment]
Oh I see.  Okay then, I'll put a little X at the top.

**Comment by linuxgurugamer** [comment]
That works, thanks

**Comment by johnfink8** [comment]
Resolved with 002a3cda2fe64891ad4127a34e645ebb61273fcc
