### ISSUE TITLE
auto-open when on the launchpad

### ISSUE THREAD

**Issue by antonytrupe** [johnfink8/GravityTurn#7]
Probably would want to make this a setting that can be opted in/out of. Maybe auto-open when focusing on any landed craft, not just the launchpad.

**Comment by johnfink8** [comment]
No, this seems like an annoying thing to have happen.  It's easy enough to click the icon to open the window.

**Comment by antonytrupe** [comment]
It's your call of course. I'm definitely annoyed at having to open it every time.
